### ISSUE TITLE
Add an input flag for cache key

### ISSUE THREAD

**Issue by fzyzcjy** [dtolnay/rust-toolchain#100]
Hi, thanks for the github actions!

Currently, this package can be used together with the "cache" github action. However, that requires a little bit of extra code. Therefore, it would be great if there is an input flag, say `cache: true`, that automatically does caching. This is inspired by https://github.com/subosito/flutter-action, which can be done like:

```
- uses: subosito/flutter-action@v2
  with:
    cache: true
```

**Comment by dtolnay** [comment]
I would prefer not to build that into this action, but it would be reasonable for someone else to maintain a more fully featured rust toolchain action that includes caching.

**Comment by fzyzcjy** [comment]
Thank you!
