### ISSUE TITLE
Run rustup toolchain install stable fails with status 127 

### ISSUE THREAD

**Issue by Bykow** [dtolnay/rust-toolchain#102]
Reopen of https://github.com/dtolnay/rust-toolchain/issues/89

I'm facing a similar issue. Running a self hosted github runner (from a win11-dev machine that I have control of). The runner supports $GITHUB_PATH.

I don't understand why this line is present https://github.com/dtolnay/rust-toolchain/blob/master/action.yml#L68

Why not install rustup on windows ?

**Comment by placintaalexandru** [comment]
Hello @Bykow 

For windows the script's url is https://win.rustup.rs/

The runner on the line you sent retrieves from https://sh.rustup.rs/ which is for unix

**Comment by dtolnay** [comment]
I would recommend adding your own step in your workflow to install rustup on your self-hosted Windows runner.

Once you have Windows rustup installation commands that have been working reliably for a while, feel free to send a PR.
