### ISSUE TITLE
Any reason `v1` tag is not updated?

### ISSUE THREAD

**Issue by bukowa** [dtolnay/rust-toolchain#114]
https://github.com/dtolnay/rust-toolchain/tree/v1

**Comment by dtolnay** [comment]
`v1` is not a supported way to use the action (#45).

**Comment by bukowa** [comment]
> `v1` is not a supported way to use the action (#45).

Is there any chance to change it? It breaks default configuration for things like `renovate` see ex. https://github.com/bukowa/ck3oop/pull/13 where it tries to update `v1` tag backwards.
