### ISSUE TITLE
Repository name is different when using Forgejo runner

### ISSUE THREAD

**Issue by yanderemine54** [dtolnay/rust-toolchain#118]
The documentation uses the repository `dtolnay/rust-toolchain` which doesn't work with Forgejo runners.

**Comment by dtolnay** [comment]
I don't know anything about Forgejo runners, so this is something you would need to figure out on your own.

**Comment by yanderemine54** [comment]
This is something I figured out, but just added documentation for this specific case, as this repo is mirrored on Forgejo.
