### ISSUE TITLE
Feature request: allow the user to customize the installation path

### ISSUE THREAD

**Issue by 06393993** [dtolnay/rust-toolchain#120]
https://github.com/dtolnay/rust-toolchain/pull/108 always sets the `CARGO_HOME` environment, which prevents the user from [customizing where to install](https://rust-lang.github.io/rustup/installation/index.html#choosing-where-to-install).

I am wondering if the upstream is willing to accept a PR to only set the `CARGO_HOME` environment variable if the `CARGO_HOME` environment is not set? Thanks!

If so the patch will look like

```
diff --git a/action.yml b/action.yml
index 23c6000..83f8062 100644
--- a/action.yml
+++ b/action.yml
@@ -60,8 +60,10 @@ runs:
       shell: bash

     - run: |
-        : set $CARGO_HOME
-        echo CARGO_HOME=${CARGO_HOME:-${{runner.os == 'Windows' && '$USERPROFILE' || '$HOME'}}/.cargo} >> $GITHUB_ENV
+        : set $CARGO_HOME if not set
+        if [[ -z "$CARGO_HOME" ]]; then
+          echo CARGO_HOME=${CARGO_HOME:-${{runner.os == 'Windows' && '$USERPROFILE' || '$HOME'}}/.cargo} >> $GITHUB_ENV
+        fi
       shell: bash

     - run: |
```

Details about my use case:
<details>
My use case is that, I want to run cargo test in not-elevated mode on Windows Github hosted runners. However, the default installation path for the Rust toolchain is in an admin folder, which is `C:\Users\runneradmin\.cargo\bin\cargo.exe`. As a result, it is an access denied error if I try to run the cargo executable from a not-elevated mode.
</details>

EDIT: only this won't work. We need to reinstall rustup with those 2 envs set.

**Comment by 06393993** [comment]
This won't work,

**Comment by wackbyte** [comment]
The step says `CARGO_HOME=${CARGO_HOME:- ... }`, using [parameter expansion](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html) to only set the variable to `$HOME/.cargo` if it is not already set.
