### ISSUE TITLE
Support for Windows ARM64 runners

### ISSUE THREAD

**Issue by anagri** [dtolnay/rust-toolchain#124]
the action is failing -
```
    - name: install Rust stable
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: aarch64-pc-windows-msvc
```

The Windows ARM 64 runners can be enabled from <Github Org> > Settings > Runners > New Runner > New Github Hosted Runner > Windows ARM64

the dtolnay/rust-toolchain@stable is failing with error message - `bash: command not found`

checkout for an actual run - https://github.com/BodhiSearch/rust-multiplatform/actions/runs/11520382847/job/32071558364

below is the log from the github action - 
```
Run actions/cache@v3
  with:
    path: target
  
    key: Windows-cargo-target-6e4035e9619ee15505419a740b[24](https://github.com/BodhiSearch/rust-multiplatform/actions/runs/11520382847/job/32071558364#step:3:26)073a839e077d70e087ce59c1f4c8e130f04d
    restore-keys: Windows-cargo-target-
  
    enableCrossOsArchive: false
    fail-on-cache-miss: false
    lookup-only: false
  env:
    CACHE_ON_FAILURE: false
    CARGO_INCREMENTAL: 0
  
Cache not found for input keys: Windows-cargo-target-6e4035e9619ee15505419a740b24073a839e077d70e087ce59c1f4c8e1[30](https://github.com/BodhiSearch/rust-multiplatform/actions/runs/11520382847/job/32071558364#step:3:32)f04d, Windows-cargo-target-
Run dtolnay/rust-toolchain@stable
  with:
    targets: aarch64-pc-windows-msvc
    toolchain: stable
  env:
    CACHE_ON_FAILURE: false
    CARGO_INCREMENTAL: 0
Run : parse toolchain version
  : parse toolchain version
  if [[ $toolchain =~ ^stable' '[0-9]+' '(year|month|week|day)s?' 'ago$ ]]; then
    if [[ Windows == macOS ]]; then
      echo "toolchain=1.$((($(date -v-$(sed 's/stable \([0-9]*\) \(.\).*/\1\2/' <<< $toolchain) +%s)/60/60/24-16569)/7/6))" >> $GITHUB_OUTPUT
    else
      echo "toolchain=1.$((($(date --date "${toolchain#stable }" +%s)/60/60/24-16569)/7/6))" >> $GITHUB_OUTPUT
    fi
  elif [[ $toolchain =~ ^stable' 'minus' '[0-9]+' 'releases?$ ]]; then
    echo "toolchain=1.$((($(date +%s)/60/60/24-16569)/7/6-${toolchain//[^0-9]/}))" >> $GITHUB_OUTPUT
  else
    echo "toolchain=$toolchain" >> $GITHUB_OUTPUT
  fi
  Error: bash: command not found
```

**Comment by dtolnay** [comment]
This is caused by https://github.com/actions/runner-images/issues/10479. You need a change in the runner image, not this repo.

**Comment by oberrich** [comment]
A working CI action for Rust `bindgen` on native ARM64 runners can be found at **[@delulu-hq/phnt-rs/.github/workflows/rust.yml](https://github.com/delulu-hq/phnt-rs/blob/master/.github/workflows/rust.yml)**.

This currently requires downloading and installing
- Git for Windows (Bash)
- LLVM (Clang 19, required for `bindgen`, MSVC bundled version has [**Clang 18 bug**](https://github.com/llvm/llvm-project/pull/93235))
- Visual Studio 2022 Build Tools 
- Rust (nightly)

_See also: https://github.com/actions/partner-runner-images/issues/19#issuecomment-2569992032_
