### ISSUE TITLE
Support hash-based pinning of action version

### ISSUE THREAD

**Issue by AliSajid** [dtolnay/rust-toolchain#126]
Hi. I am trying to establish some security best practices in my work and personal projects. One of the requirements for those is that GitHub actions should be pinned by their hash, instead of tag. This is both [recommended by GitHub](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions) and part of the [OSSF Scorecard](https://github.com/ossf/scorecard).

I have implemented it for everything except this action, which also happens to be the best way to install Rust in the GitHub hosted runners. Would it be possible for you to integrate some kind of versioning-like strategy that allows for pinning the dependency? Particularly for the `stable`, `beta` and `nightly` versions of Rust?

**Comment by yonas** [comment]
Ran into this issue as well.

**Comment by dtolnay** [comment]
As far as I can tell, this is already supported. You can pick whatever commit hash from the history of the master branch you want, and pass whatever `with: toolchain:` you want including stable or beta or nightly.

@AliSajid would you mind clarifying more what the request is?

**Comment by AliSajid** [comment]
@dtolnay Thank you. That's what I am doing right now. The problem then becomes whether the commit I've picked is stable or not. Although that is unlikely, given you, but it is still possible that a particular commit might have a regression or a bug. Is it possible to have a way to mark the commits as stable or not with a different series of tags in addition to the moving tag scheme you have here?

**Comment by dtolnay** [comment]
I don't make a distinction between commits that go to master which are ready to use vs not ready to use. The readme recommends using `dtolnay/rust-toolchain@master` and all the rest of the tags (`@1.83.0` etc) are always rebased on master too. If you want to make your own determination about what commit is ready to use, you could review recent commits yourself before upgrading your pin, or you could trail master by some number of months.

**Comment by AliSajid** [comment]
Thank you. That makes sense.
