### ISSUE TITLE
Update Rust versions

### ISSUE THREAD

**Issue by yonas** [dtolnay/rust-toolchain#130]
## Versions
- Stable: [1.83.0](https://releases.rs/docs/1.83.0)
- Beta: [1.84.0](https://releases.rs/docs/1.84.0)
- Nightly: [1.85.0](https://releases.rs/docs/1.85.0)

**Comment by yonas** [comment]
Then why is it pulling in such an old version of Rust?

**Comment by dtolnay** [comment]
`toolchain: stable` pulls in the current stable release, which is 1.82.0 currently. See https://github.com/dtolnay/rust-toolchain/actions/runs/12022466360/job/33514729626#step:6:9.
