### ISSUE TITLE
[Bug] Action failure due to deprecated command

### ISSUE THREAD

**Issue by rami3l** [dtolnay/rust-toolchain#4]
In [this test](https://github.com/rami3l/pacaptr/runs/1419760872?check_suite_focus=true) which uses a `fedora` container, the workflow halted on error running the `rust-toolchain` action.

Following the [link](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) given in the error message, it seems that this issue is caused by the use of a deprecated command `add-path`.

Complete error message:

```
25 Error: Unable to process command '::add-path::/github/home/.cargo/bin' successfully.
26 Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

Thanks in advance! 🙏

**Comment by dtolnay** [comment]
Pushed a fix that I believe fixes this (https://github.com/dtolnay/rust-toolchain/commit/4d9a2b11c1b557c1fd9fd081623b64ed76e3b6a0; see https://github.com/actions-rs/toolchain/issues/124). Could you retrigger your job and indicate whether it passes again?

**Comment by rami3l** [comment]
@dtolnay Yes, it's working alright. Many thanks!
