### ISSUE TITLE
Support rustup profiles (particularly `minimal`)

### ISSUE THREAD

**Issue by Fishrock123** [dtolnay/rust-toolchain#41]
It would be nice if this action supported rustup's `minimal` [profile](https://rust-lang.github.io/rustup/concepts/profiles.html) option. Sometimes you just don't need to download everything!

And i say "profiles" in general because, well, that mirrors the rustup option, though I doubt anyone is ever going to use `complete` for obvious reasons, so this is practically speaking only about the `minimal` profile option.

**Comment by dtolnay** [comment]
It uses `minimal` because that is what is supposed to be used in CI. From the page you linked:

> *It's recommended to use this component […] in CI.*

**Comment by Fishrock123** [comment]
Ah. I just saw that reading the action script bits as well.

It would be nice if the docs could mention that it used `minimal` by default.
