### ISSUE TITLE
Consider .tool-versions

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [dtolnay/rust-toolchain#42]
Would you accept a pull request that added support for [asdf](https://github.com/asdf-vm/asdf)'s `.tool-versions`. The use case is for projects using that file to not have to specify versions twice (once on that file, which is usually used for local development, and once again on the action, as an input). It'd reduce maintenance, for consumers, as well as make it less error prone.

**Comment by dtolnay** [comment]
I am not interested in supporting that.
