### ISSUE TITLE
Creation of 1.70 branches triggered dependabot update

### ISSUE THREAD

**Issue by bgianfo** [dtolnay/rust-toolchain#43]
Filing this as an FYI, it looks like the 1.70, 1.69, and other branches were created in preparation for far into the future versions rust.

However depandabot doesn't know that these are yet to be released, and happily sent PR's to try to update repositories using this action to try to use a non existent 1.70 rust toolchain. Example: https://github.com/martian-lang/martian-rust/pull/263 

I'm not sure what the real solution is here, or if it's really even a problem, but just wanted to let you know in case this was an oversight.

**Comment by dtolnay** [comment]
Thanks for the notice. I plan to continue pushing numbered branches in advance of Rust releases, so this would be between you and Dependabot how to make it stop opening those PRs (or use a different action).
