### ISSUE TITLE
Consider updating v1 tag

### ISSUE THREAD

**Issue by taiki-e** [dtolnay/rust-toolchain#45]
When specifying the toolchain version with `toolchain` input option (e.g., when using the old nightly toolchain, when using matrix), I'm currently using the `v1` tag of this action. (I don't want to use the `master` branch because I want to avoid breakage due to unreleased changes.)

However, the `v1` tag does not seem to have been updated and I [get "`set-output` command is deprecated and will be disabled soon"](https://github.com/crossbeam-rs/crossbeam/actions/runs/3606348602/jobs/6077600188) warnings which have already been fixed in other releases (branches).

Is it possible to update the `v1` tag like other releases (branches)? (switching from tag to branch would also may work)
Or is the `v1` tag considered deprecated and it is recommended to use the `master` branch which may contain unreleased changes or another branch?

**Comment by dtolnay** [comment]
The `v1` tag only exists so that the action gets a page on https://github.com/marketplace/actions. (And it has to be a tag for that to happen.) I am not interested in updating it. `master` and all the other branches (`stable`, `1.65` etc) are the only supported and documented way to use the action.

**Comment by taiki-e** [comment]
Oh, I didn't realize that was an unsupported usage in the first place. (As shown in the following image, pressing the button "Use the latest version" on the marketplace page will suggest the `v1` tag.)

<img width="745" alt="marketplace" src="https://user-images.githubusercontent.com/43724913/205430372-250bf48c-11fb-4081-b1c1-cb7358f3420e.png">

Anyway, if it is not supported in the first place, this issue can be closed. (Although I may need to revisit the use of this action on a project I'm involved in, but that is due to my somewhat pedantic sticking to the stability of the CI, and is probably not a general expectation for this action.)
