### ISSUE TITLE
Emit Rust release in an Actions output

### ISSUE THREAD

**Issue by GeorgeHahn** [dtolnay/rust-toolchain#47]
It would be helpful to report the Rust release in an Action output variable. For example, I have a scenario where I'm using the latest `stable` and would like to display the compiler version for diagnostics.

I can contribute this if you like the idea!

I don't personally have a need for them, but I can add the LLVM version, commit date, & hash as well.

**Comment by dtolnay** [comment]
I would prefer not to build this into this project. For your use case hopefully you can parse the output of rustc --version in your own code.
