### ISSUE TITLE
Register problem matchers

### ISSUE THREAD

**Issue by jyn514** [dtolnay/rust-toolchain#50]
Github has an option to register "problem matchers": https://github.com/actions/toolkit/blob/master/docs/commands.md#problem-matchers
These make the warnings/errors from rust tools show up as annotations in the PR diff, instead of having to open the job logs:
![image](https://user-images.githubusercontent.com/23638587/209480613-ff12a6b6-9ccf-49c5-bfdd-f6723c9c2eed.png)

It would be nice for `rust-toolchain` to automatically register these when it installs the toolchain; there's an example of how to do so here (note that you'll also need the `.github/rust.json` file in that repository): https://github.com/hecrj/setup-rust-action/blob/50a120e4d34903c2c1383dec0e9b1d349a9cc2b1/src/main.ts#L34

**Comment by dtolnay** [comment]
I prefer reading the compiler's rendered diagnostics via the console output of the job, so I would prefer not to support this.
