### ISSUE TITLE
Support for Github Enterprise server

### ISSUE THREAD

**Issue by vineeth-asml** [dtolnay/rust-toolchain#63]
Hello @dtolnay , 

We would like to use you action in our enterprise server instance of GitHub. Due to the network restrictions we are not able to use it at the moment. 
Download of file [sh.rustup.rs](https://github.com/dtolnay/rust-toolchain/blob/9cd00a88a73addc8617065438eff914dd08d0955/action.yml#L65) won't work in our case since we don't have access to internet. 

Would you like to add an extra input with a different source for this file download with default to https://sh.rustup.rs ? If so i can propose the change with a pull request

**Comment by dtolnay** [comment]
I would prefer not to support this.
