### ISSUE TITLE
Reconsider support for rust-toolchain.toml

### ISSUE THREAD

**Issue by dsherret** [dtolnay/rust-toolchain#77]
I have just noticed that this project does not support the rust-toolchain.toml file because the latest rust release broke all our CI runs because of sparse registry support being opted into by this action.

In https://github.com/dtolnay/rust-toolchain/issues/12 (now locked) it was mentioned that you would prefer to not add support for rust-toolchain.toml files, but it is valuable to only have the version defined in one place (we often found people forgot to keep the version between the yml and toolchain file in sync). Is there a reason not to add this?

**Comment by dtolnay** [comment]
I'd still prefer not to support it.

**Comment by dsherret** [comment]
That's too bad. I'll create my own basic solution.

**Comment by dsherret** [comment]
Ok, I really needed this so I created https://github.com/dsherret/rust-toolchain-file based on a fork of this for anyone who wants this functionality.
