### ISSUE TITLE
@nightly on windows issue ?

### ISSUE THREAD

**Issue by greyna** [dtolnay/rust-toolchain#82]
Hello,

First thank you for all the awesome work :)

I believe there is an issue when using @ nightly on windows as you can see on this run of my repo : https://github.com/greyna/greyna_bevy_tower_defense/actions/runs/4709717855

It might be a very easy to fix issue however I'm a fresh beginner with github actions and I don't know windows shell programming either...

I hope it's a real problem whose fix could benefit everyone and not just a problem of my own!

Cheers,

Arthur

**Comment by dtolnay** [comment]
Seems like a Windows-specific GitHub bug. Your workflow has an [env variable called $TOOLCHAIN](https://github.com/greyna/greyna_bevy_tower_defense/actions/runs/4709717855/workflow#L12) and that corrupted the name that GitHub passed for [this other env variable](https://github.com/dtolnay/rust-toolchain/blob/b44cb146d03e8d870c57ab64b80f04586349ca5d/action.yml#L48). On macos-latest and ubuntu-latest it correctly passes $toolchain but on windows-latest $toolchain does not get set.

**Comment by greyna** [comment]
Thank you this is quite surprising!
