### ISSUE TITLE
Install of clippy from the beta channel is failing

### ISSUE THREAD

**Issue by hovinen** [dtolnay/rust-toolchain#84]
Today our [CI pipeline](https://github.com/google/googletest-rust/actions/runs/4912752533/jobs/8773339269) started giving the following error for the clippy job on the beta channel:

```
Run dtolnay/rust-toolchain@b44cb146d03e8d870c57ab64b80f04586349ca5d
Run : parse toolchain version
Run : construct rustup command line
Run : install rustup if needed
Run rustup toolchain install beta --component clippy --profile minimal --no-self-update
info: syncing channel updates for 'beta-x86_64-unknown-linux-gnu'
info: latest update on 2023-05-08, rust version 1.70.0-beta.4 (2013813b6 2023-05-07)
error: component 'clippy' for target 'x86_64-unknown-linux-gnu' is unavailable for download for channel 'beta'
```

Not sure whether this is just a temporary glitch, but perhaps something needs to be updated in this action.

**Comment by taiki-e** [comment]
upstream issue: https://github.com/rust-lang/rust/issues/111340

**Comment by hovinen** [comment]
Thanks! The linked issue has now been fixed and I can confirm that the action is working again.
