### ISSUE TITLE
Failing log level tests after switching to rust-toolchain

### ISSUE THREAD

**Issue by drager** [dtolnay/rust-toolchain#85]
Hello, we recently switched to `dtolnay/rust-toolchain` from `actions-rs/toolchain@v1` in [wasm-pack](https://github.com/rustwasm/wasm-pack/commit/3073db8f18fcd452404929d22762389b50d2cfe7) and now some of our tests are failing (running fine locally with the same rust version).

The failures are available here:
https://github.com/rustwasm/wasm-pack/actions/runs/5145936487/jobs/9264280002
failures:
    log_level::log_level_error
    log_level::log_level_info
    log_level::log_level_warn

The test code: https://github.com/rustwasm/wasm-pack/blob/6af9f2275003759d2a746c1f2533af8e30bbee64/tests/all/log_level.rs#L43-L94

Do you know anything about this and possibly how we can solve this? Feels a bit weird that our tests are failing after switching and are only doing so in CI and that's mainly why I'm opening this issue here.

Thanks!

**Comment by dtolnay** [comment]
https://github.com/rustwasm/wasm-pack/pull/1294

**Comment by drager** [comment]
Thank you very much!
