### ISSUE TITLE
Consider `dtolnay/rust-toolchain@rustup`

### ISSUE THREAD

**Issue by StackOverflowExcept1on** [dtolnay/rust-toolchain#86]
Hi, we are using your `dtolnay/rust-toolchain@master` at https://github.com/gear-tech/gear. Our project uses pinned toolchain in `rust-toolchain.toml`. So when you run this action on github, it installs an unused toolchain.

Could you add something like `dtolnay/rust-toolchain@rustup` to install just rustup? For example, action can install rustup if needed and exit.
https://github.com/dtolnay/rust-toolchain/blob/b44cb146d03e8d870c57ab64b80f04586349ca5d/action.yml#L62-L69

**Comment by dtolnay** [comment]
I would prefer not to build this into this project. But it would be reasonable for someone else to support.

**Comment by mkroening** [comment]
> But it would be reasonable for someone else to support.

There are many alternatives available that build upon this action to support `rust-toolchain.toml`. For example, I just published [`mkroening/rust-toolchain-toml`](https://github.com/mkroening/rust-toolchain-toml), which parses the TOML using [yq](https://github.com/mikefarah/yq).
