### ISSUE TITLE
Suggestion: Install a problem matcher for cargo messages

### ISSUE THREAD

**Issue by antifuchs** [dtolnay/rust-toolchain#93]
GitHub actions can install [problem matchers](https://github.com/actions/toolkit/blob/main/docs/problem-matchers.md) that extract error/info/warning messages from a workflow run and put them into the "Files Changed" tab (see [here](https://github.com/progval/unicode_names2/pull/19/files) for an example that's generated by the matcher in [actions-rs/cargo](https://github.com/actions-rs/cargo/blob/9e120dd99b0fbad1c065f686657e914e76bd7b72/.matchers/rust.json)).

The `setup-go` action and others already install problem matchers for compiler messages, and I think it would be really cool if rust-toolchain could do the same. (actions-rs/cargo is MIT licensed just like this repo, so it might be as easy as dropping the `::add-matcher` line and the matcher JSON file in here.)

**Comment by dtolnay** [comment]
This was proposed previously in #50.

**Comment by antifuchs** [comment]
Understandable! Thanks for the link, I didn't find that in a cursory search
