### ISSUE TITLE
Question: Does this action include new minor releases without any patches?

### ISSUE THREAD

**Issue by cnpryer** [dtolnay/rust-toolchain#98]
Thanks for building this! I love all the work you do. It's very appreciated.

Hopefully a quick question -- sorry if I'm misunderstanding something. IIUC, for example, 1.73.0 won't be available until 1.73.1 is made available. https://github.com/dtolnay/rust-toolchain/blob/439cf607258077187679211f12aa6f19af4a0af7/scripts/update-revs.sh#L10-L18

Is that correct? For context I noticed this when trying to update my project to use the 1.73 channel https://github.com/cnpryer/huak/actions/runs/6448450600/job/17505798048?pr=756.

**Comment by mkroening** [comment]
I think the issue with your CI is that `dtolnay/rust-toolchain@stable` installs `1.73.0` but your `rust-toolchain.toml` uses the `1.73` channel, which is a different thing, as far as I know.

**Comment by cnpryer** [comment]
Gotcha. Thanks for the response. I ended up just moving my project to `nightly` anyway, so I'll close this.
