### ISSUE TITLE
 CARGO_REGISTRIES_CRATES_IO_PROTOCOL breaks ci

### ISSUE THREAD

**Issue by Juanito87** [dtolnay/rust-toolchain#99]
The way the env var is set ` CARGO_REGISTRIES_CRATES_IO_PROTOCOL`, breaks the ci (github actions) using `channel : nightly-2023-01-16`.

The error message shows: 
```
Caused by:
  Unable to update registry `crates-io`

Caused by:
  usage of sparse registries requires `-Z sparse-registry`
```
Proposed solution:

* enable a flag to avoid setting this env var.

**Comment by dtolnay** [comment]
CARGO_REGISTRIES_CRATES_IO_PROTOCOL got stabilized in Cargo 1.68, so this failure is likely specific to early nightlies from the 1.68 release cycle before the stabilization got landed. I don't plan to add logic to support that specific range of nightlies, so you would need to avoid this issue by choosing a newer toolchain.
